---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: redmine:4.1.1
        env:
          - name: REDMINE_DB_POSTGRES
            value: database
          - name: REDMINE_DB_USERNAME
            value: redmine
          - name: REDMINE_DB_PASSWORD
            valueFrom: 
               secretKeyRef:
                 key: REDMINE_DB_PASSWORD
                 name: redmine-secret
          - name: REDMINE_DB_DATABASE
            value: testdatabase
          - name: REDMINE_SECRET_KEY_BASE
            valueFrom:
                secretKeyRef:
                  key: REDMINE_SECRET_KEY_BASE
                  name: redmine-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
